#logging:
#  level:
#    root: ERROR
#    org:
#      springframework:
#        web: ERROR
#      hibernate: ERROR
# Этот способ отключения логирования не работает. Работает способ отключения через файл logback.xml.
